apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::038304963916:role/eksctl-custom-jwt-api-nodegroup-n-NodeInstanceRole-1ICNBGN4B7KLJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::038304963916:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-09T18:42:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1498"
  uid: b5db85e3-e6e4-4944-abea-0c5b5c30afa6
